apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: secret-whoami-oidc-client-secret
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 1
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kubernetes-j8-fh
        secretName: WHOAMI_OIDC_CLIENT_SECRET
        envSlug: helheim
        secretsPath: "/"
      credentialsRef:
        secretName: secret-machine-identity
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: secret-whoami-oidc-client-secret
      secretNamespace: whoami
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          api-key: "{{ .WHOAMI_OIDC_CLIENT_SECRET.Value }}"
