apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "traefik.houseofix.online"
spec:
  parentRefs:
    - name: traefik
      kind: Gateway
  hostnames:
    - "traefik.houseofix.online"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/dashboard"
        - path:
            type: PathPrefix
            value: "/api"
      backendRefs:
        - name: traefik
          port: 9000
