apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    app: traefik
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: core
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 38.0.0
      helm:
        valueFiles:
          - $values/clusters/helheim/core/traefik/values.yaml
    - repoURL: "https://github.com/MichielVanHerreweghe/gitops.git"
      targetRevision: HEAD
      ref: values
    # - repoURL: "https://github.com/MichielVanHerreweghe/gitops.git"
    #   path: clusters/helheim/core/traefik/manifests
    #   targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
