apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  labels:
    app: envoy-gateway
spec:
  destination:
    namespace: envoy-gateway
    server: https://kubernetes.default.svc
  project: core
  sources:
    - chart: gateway-crds-helm
      repoURL: oci://docker.io/envoyproxy/gateway-crds-helm
      targetRevision: v1.6.1
      helm:
        valueFiles:
          - $values/clusters/helheim/core/envoy-gateway/values.yaml
    - repoURL: "https://github.com/MichielVanHerreweghe/gitops.git"
      targetRevision: HEAD
      ref: values
    - chart: gateway-helm
      repoURL: oci://docker.io/envoyproxy/gateway-helm
      targetRevision: v1.6.1
    - repoURL: "https://github.com/MichielVanHerreweghe/gitops.git"
      path: clusters/helheim/core/envoy-gateway/manifests
      targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
