apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy
  annotations:
    cert-manager.io/cluster-issuer: cloudflare
    cert-manager.io/issue-temporary-certificate: "true"
    external-dns.alpha.kubernetes.io/target: "ip.houseofix.online"
spec:
  gatewayClassName: envoy
  listeners:
    - name: whoami-https
      protocol: HTTPS
      port: 443
      hostname: "whoami.houseofix.online"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: envoy-tls-cert
            namespace: envoy-gateway
